// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.2
// source: checkout_api.proto

package checkout

import (
	_ "apis/hertz_gen/api"
	cart "apis/hertz_gen/cart"
	order "github.com/BeroKiTeer/MyGoMall/common/kitex_gen/order"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token         string           `protobuf:"bytes,1,opt,name=token,proto3" form:"token" json:"token,omitempty" query:"token"`
	Firstname     string           `protobuf:"bytes,2,opt,name=firstname,proto3" form:"firstname" json:"firstname,omitempty" query:"firstname"`                     // 用户的名字
	Lastname      string           `protobuf:"bytes,3,opt,name=lastname,proto3" form:"lastname" json:"lastname,omitempty" query:"lastname"`                         // 用户的姓氏
	Email         string           `protobuf:"bytes,4,opt,name=email,proto3" form:"email" json:"email,omitempty" query:"email"`                                     // 用户的邮箱
	Address       *order.Address   `protobuf:"bytes,5,opt,name=address,proto3" form:"address" json:"address,omitempty" query:"address"`                             // 用户的地址信息
	Items         []*cart.CartItem `protobuf:"bytes,6,rep,name=items,json=cart_item,proto3" form:"items" json:"items,omitempty" query:"items"`                      //增加商品清单
	PaymentMethod string           `protobuf:"bytes,7,opt,name=payment_method,proto3" form:"payment_method" json:"payment_method,omitempty" query:"payment_method"` //支付方式
}

func (x *CheckoutReq) Reset() {
	*x = CheckoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkout_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutReq) ProtoMessage() {}

func (x *CheckoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutReq.ProtoReflect.Descriptor instead.
func (*CheckoutReq) Descriptor() ([]byte, []int) {
	return file_checkout_api_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckoutReq) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *CheckoutReq) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *CheckoutReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckoutReq) GetAddress() *order.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CheckoutReq) GetItems() []*cart.CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckoutReq) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CheckoutResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string `protobuf:"bytes,1,opt,name=order_id,proto3" form:"order_id" json:"order_id,omitempty" query:"order_id"`                 // 订单 ID
	UrlCallback string `protobuf:"bytes,2,opt,name=url_callback,proto3" form:"url_callback" json:"url_callback,omitempty" query:"url_callback"` //用于重定向的url
	Amount      int64  `protobuf:"varint,3,opt,name=amount,json=url_callback,proto3" form:"amount" json:"amount,omitempty" query:"amount"`      //价格
}

func (x *CheckoutResp) Reset() {
	*x = CheckoutResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkout_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResp) ProtoMessage() {}

func (x *CheckoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_checkout_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResp.ProtoReflect.Descriptor instead.
func (*CheckoutResp) Descriptor() ([]byte, []int) {
	return file_checkout_api_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CheckoutResp) GetUrlCallback() string {
	if x != nil {
		return x.UrlCallback
	}
	return ""
}

func (x *CheckoutResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_checkout_api_proto protoreflect.FileDescriptor

var file_checkout_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xef, 0x01, 0x0a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x12, 0x26, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x6c, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x72, 0x6c, 0x5f, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x72, 0x6c, 0x5f,
	0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x72, 0x6c, 0x5f, 0x63, 0x61,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x32, 0x67, 0x0a, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x08, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x11, 0xd2, 0xc1,
	0x18, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x42,
	0x1d, 0x5a, 0x1b, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x5f, 0x67, 0x65,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_checkout_api_proto_rawDescOnce sync.Once
	file_checkout_api_proto_rawDescData = file_checkout_api_proto_rawDesc
)

func file_checkout_api_proto_rawDescGZIP() []byte {
	file_checkout_api_proto_rawDescOnce.Do(func() {
		file_checkout_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_checkout_api_proto_rawDescData)
	})
	return file_checkout_api_proto_rawDescData
}

var file_checkout_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checkout_api_proto_goTypes = []interface{}{
	(*CheckoutReq)(nil),   // 0: api.checkout.checkoutReq
	(*CheckoutResp)(nil),  // 1: api.checkout.checkoutResp
	(*order.Address)(nil), // 2: order.Address
	(*cart.CartItem)(nil), // 3: cart.CartItem
}
var file_checkout_api_proto_depIdxs = []int32{
	2, // 0: api.checkout.checkoutReq.address:type_name -> order.Address
	3, // 1: api.checkout.checkoutReq.items:type_name -> cart.CartItem
	0, // 2: api.checkout.checkoutService.Checkout:input_type -> api.checkout.checkoutReq
	1, // 3: api.checkout.checkoutService.Checkout:output_type -> api.checkout.checkoutResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_checkout_api_proto_init() }
func file_checkout_api_proto_init() {
	if File_checkout_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_checkout_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkout_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checkout_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkout_api_proto_goTypes,
		DependencyIndexes: file_checkout_api_proto_depIdxs,
		MessageInfos:      file_checkout_api_proto_msgTypes,
	}.Build()
	File_checkout_api_proto = out.File
	file_checkout_api_proto_rawDesc = nil
	file_checkout_api_proto_goTypes = nil
	file_checkout_api_proto_depIdxs = nil
}
