// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	cart "apis/biz/router/cart"
	checkout "apis/biz/router/checkout"
	order "apis/biz/router/order"
	payment "apis/biz/router/payment"
	product "apis/biz/router/product"
	"apis/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)

	payment.Register(r)

	checkout.Register(r)

	product.Register(r)

	user.Register(r)
	cart.Register(r)
}
