version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"  # Elasticsearch 是基于 Java（JVM） 开发的，因此它的内存管理依赖 JVM 的垃圾回收（GC）机制。
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: logstash:7.17.13
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  # Filebeat 采集日志端口
      - "9600:9600"  # Logstash API 监控端口
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk

  kibana:
    image: kibana:7.17.13
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk

volumes:
  es_data:
    driver: local

networks:
  elk:
    driver: bridge
