// Code generated by hertz generator.

package pay

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _payMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cardpayMw() []app.HandlerFunc {
	// your code...
	return nil
}
