// Code generated by hertz generator.

package pay

import (
	"context"

	pay "apis/hertz_gen/api/pay"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CardPay .
// @router /api/pay/card_pay [POST]
func CardPay(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pay.CardPayReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(pay.CardPayResp)

	c.JSON(consts.StatusOK, resp)
}
