// Code generated by hertz generator.

package payment

import (
	"apis/biz/utils"
	payment "apis/hertz_gen/api/payment"
	"apis/rpc"
	"context"
	"github.com/BeroKiTeer/MyGoMall/common/kitex_gen/auth"
	payment_kitex "github.com/BeroKiTeer/MyGoMall/common/kitex_gen/payment"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Charge .
// @router /api/pay/card_pay [POST]
func Charge(ctx context.Context, c *app.RequestContext) {
	var err error
	var req payment.ChargeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		hlog.Errorf("error:%v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	err = utils.BindJson(c, &req)
	// 获取请求头的token
	token := c.Request.Header.Get("Authorization")
	if token == "" {
		hlog.Errorf("token is empty")
		utils.SendErrResponse(ctx, c, consts.StatusUnauthorized, err)
		return
	}

	// 获取用户id
	userID, err := rpc.AuthClient.DecodeToken(ctx, &auth.DecodeTokenReq{Token: token})
	if err != nil {
		hlog.Errorf("error:%v", err)
		utils.SendErrResponse(ctx, c, consts.StatusInternalServerError, err)
		return
	}
	hlog.Infof("sendInHertz")
	resp, err := rpc.PaymentClient.ChargeByThirdParty(ctx, &payment_kitex.ChargeByThirdPartyReq{
		Amount:  req.Amount,
		OrderId: req.OrderId,
		UserId:  uint32(userID.UserId),
		Way:     req.Way,
	})

	if err != nil {
		hlog.Errorf("error:%v", err)
		utils.SendErrResponse(ctx, c, consts.StatusInternalServerError, err)
	}

	utils.SendSuccessResponse(ctx, c, consts.StatusOK, resp)
}
